name: 'Publish on Release'
on:
  release:
    types: ["created"]

jobs:
  publish-to-vscode-marketplace:
    name: 'Publish to VS Code Extension Marketplace'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

  publish-to-openvsx:
    name: 'Publish to Open VSX'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPENVSX_TOKEN }}